### ISSUE TITLE
Winter Beverage Additions

### ISSUE THREAD

**Issue by githubteacher** [githubschool/pm-cookbook#4]
The following beverage recipes need to be added to the beverages:
### Additions
- [ ] Hot Spiced Cider - #5
- [ ] Sparkling Punch - #6
- [ ] Hot Cocoa Mix - #7
- [ ] Hot Apple Cider - #8 
- [ ] Gluehwein - #9 
- [ ] Eggnog - #10
- [ ] Hot Spiced Cranberry Cider - #11
- [ ] Gloomy Day Smoothie - #12
- [ ] Coffeeless Pumpkin Latte - #13
- [ ] Colonial Hot Buttered Rum - #14
- [ ] Wassail Punch - #15
- [ ] Kale and Banana Smoothie - #16
- [ ] Mexican Hot Chocolate - #17
- [ ] Holiday Punch - #18
### Corrections
- [ ] Correct Lemon Icebox Pie - #3
